# Generated by Django 5.0 on 2023-12-09 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('comment', models.CharField(max_length=150, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='Начало времени рассылки')),
                ('finish_time', models.DateField(blank=True, null=True, verbose_name='Конец времени рассылки')),
                ('send_frequency', models.CharField(blank=True, choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], max_length=20, null=True, verbose_name='Периодичность')),
                ('mailing_status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('done', 'Завершена')], max_length=20, verbose_name='Статус')),
                ('title_message', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('body_message', models.TextField(blank=True, null=True, verbose_name='Тело письма')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Дата последней рассылки')),
                ('mailing_clients', models.ManyToManyField(to='mailing.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'permissions': [('deactivate_mailing', 'Can deactivate settings')],
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')),
                ('log_status', models.CharField(choices=[('ok', 'Успешно'), ('failed', 'Ошибка')], max_length=20, verbose_name='Статус попытки')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ сервера')),
                ('log_mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылки',
            },
        ),
    ]
